# Generated by Django 5.1.1 on 2024-09-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://static.vecteezy.com/system/resources/previews/010/826/341/original/vacation-icon-isolated-on-transparent-background.png', max_length=500),
        ),
    ]
